# 使用 Python 3.11 的基底映像檔
FROM python:3.11

# 安裝 wkhtmltopdf
RUN apt-get update && apt-get install -y wkhtmltopdf

# 設置工作目錄
WORKDIR /app

# 複製 requirements.txt 並安裝依賴
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt;

# 再次手動安裝 gunicorn 以確保其存在
RUN pip install --no-cache-dir gunicorn

# 確認 gunicorn 是否已正確安裝，這行會顯示 gunicorn 的安裝路徑
RUN which gunicorn

# 複製所有文件到容器
COPY . .

# 使用環境變數 $PORT 來綁定埠號
CMD ["gunicorn", "--bind", "0.0.0.0:${PORT}", "finaltest1:app"]
